id: IFB3CF922
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T10:48:03+00:00'
last_modified: '2022-06-08T03:35:10.577099+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ74191
  title: ཤེར་ཕྱིན་སྟོང་ཕྲག་བརྒྱ་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '4115':
      image_group_id: I4CZ75579
      title: ''
      total_pages: 804
      order: 1
      base_file: 4115.txt
    912E:
      image_group_id: I4CZ75580
      title: ''
      total_pages: 798
      order: 2
      base_file: 912E.txt
    E9F9:
      image_group_id: I4CZ75581
      title: ''
      total_pages: 792
      order: 3
      base_file: E9F9.txt
    '1580':
      image_group_id: I4CZ75582
      title: ''
      total_pages: 772
      order: 4
      base_file: 1580.txt
    A429:
      image_group_id: I4CZ75583
      title: ''
      total_pages: 790
      order: 5
      base_file: A429.txt
    44E5:
      image_group_id: I4CZ75584
      title: ''
      total_pages: 804
      order: 6
      base_file: 44E5.txt
    '8244':
      image_group_id: I4CZ75585
      title: ''
      total_pages: 850
      order: 7
      base_file: 8244.txt
    4FD4:
      image_group_id: I4CZ75586
      title: ''
      total_pages: 926
      order: 8
      base_file: 4FD4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
