id: IFB3CF922
legacy_id: P005508
ocr_import_info:
  bdrc_scan_id: W4CZ74191
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T10:44:14'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T20:58:06.975323+00:00'
last_modified: 2022-09-04 05:00:53.773903
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W4CZ74191
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW4CZ74191
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཤེར་ཕྱིན་སྟོང་ཕྲག་བརྒྱ་པ།
statistics:
  ocr_word_mean_confidence_index: 0.48635610142613545
  ocr_word_median_confidence_index: 0.4399999976158142
quality: null
bases:
  I4CZ75580:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ75580
      total_pages: 798
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I4CZ75580.txt
    statistics:
      ocr_word_median_confidence_index: 0.47999998927116394
      ocr_word_mean_confidence_index: 0.5184402858679341
    legacy_id: v002
  I4CZ75582:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ75582
      total_pages: 772
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I4CZ75582.txt
    statistics:
      ocr_word_median_confidence_index: 0.4399999976158142
      ocr_word_mean_confidence_index: 0.48185650113866474
    legacy_id: v004
  I4CZ75584:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ75584
      total_pages: 804
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I4CZ75584.txt
    statistics:
      ocr_word_median_confidence_index: 0.46000000834465027
      ocr_word_mean_confidence_index: 0.49496155474998554
    legacy_id: v006
  I4CZ75583:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ75583
      total_pages: 790
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I4CZ75583.txt
    statistics:
      ocr_word_median_confidence_index: 0.5199999809265137
      ocr_word_mean_confidence_index: 0.5371582439432664
    legacy_id: v005
  I4CZ75581:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ75581
      total_pages: 792
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I4CZ75581.txt
    statistics:
      ocr_word_median_confidence_index: 0.3499999940395355
      ocr_word_mean_confidence_index: 0.41586288563419715
    legacy_id: v003
  I4CZ75586:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ75586
      total_pages: 926
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I4CZ75586.txt
    statistics:
      ocr_word_median_confidence_index: 0.46000000834465027
      ocr_word_mean_confidence_index: 0.49816613279198657
    legacy_id: v008
  I4CZ75585:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ75585
      total_pages: 850
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I4CZ75585.txt
    statistics:
      ocr_word_median_confidence_index: 0.4000000059604645
      ocr_word_mean_confidence_index: 0.45185296013875526
    legacy_id: v007
  I4CZ75579:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ75579
      total_pages: 804
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4CZ75579.txt
    statistics:
      ocr_word_median_confidence_index: 0.47999998927116394
      ocr_word_mean_confidence_index: 0.5081303048712477
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
