id: P005508
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ74191
  title: ཤེར་ཕྱིན་སྟོང་ཕྲག་བརྒྱ་པ།
  author: ''
  volumes:
    d5dcd926fe5d49f38d022bbfcfb2e907:
      image_group_id: I4CZ75579
      title: ''
      volume_number: 1
      total_pages: 804
      base_file: v001.txt
    e2efa97f85294533afb43e731449d593:
      image_group_id: I4CZ75580
      title: ''
      volume_number: 2
      total_pages: 798
      base_file: v002.txt
    385336ae14294b2cb0e873f53cb5958b:
      image_group_id: I4CZ75581
      title: ''
      volume_number: 3
      total_pages: 792
      base_file: v003.txt
    820647f55b7845caa9ba55aead7ae6d9:
      image_group_id: I4CZ75582
      title: ''
      volume_number: 4
      total_pages: 772
      base_file: v004.txt
    c8a076cf507a4cf7a450e99f47f4c6df:
      image_group_id: I4CZ75583
      title: ''
      volume_number: 5
      total_pages: 790
      base_file: v005.txt
    0adea270afe34ae38de5c232fe4ba71e:
      image_group_id: I4CZ75584
      title: ''
      volume_number: 6
      total_pages: 804
      base_file: v006.txt
    2a73920d0c80435a8e142ea8e967c8e7:
      image_group_id: I4CZ75585
      title: ''
      volume_number: 7
      total_pages: 850
      base_file: v007.txt
    bca1314041de4dc1acfe0c4d646f31f2:
      image_group_id: I4CZ75586
      title: ''
      volume_number: 8
      total_pages: 926
      base_file: v008.txt
    622b36acc6cb421c8f32b0cbcd22029a:
      image_group_id: I4CZ75587
      title: ''
      volume_number: 9
      total_pages: 0
